---
name: CI for ansible-role-sshd

on: [push]  # yamllint disable-line rule:truthy

defaults:
  run:
    working-directory: 'zstyblik.sshd'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v5
        with:
          path: 'zstyblik.sshd'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
      - name: Run yamllint
        run: |
          ./ci/run-yamllint.sh
      - name: Run ansible-lint
        run: |
          ./ci/run-ansible-lint.sh
